# .github/labeler.yml

bug:
  - '**/*.py'
  - '**/*.ctri'

documentation:
  - '**/*.md'
  - '**/*.txt'

enhancement:
  - '**/*.py'
  - '**/*.ctri'
  - 'Makefile'

help wanted:
  - '**/*.py'
  - '**/*.ctri'

update/addition:
  - '**/*.py'
  - '**/*.txt'
  - '**/*.ctri'
  - 'Makefile'
  - '.gitignore'
  - '.gitattributes'
  - '.github/workflows/**/*.yml'
