"""NASM code generator for C△ compiler asm blocks.

This module generates NASM-compatible assembly files (.s) from AsmBlock AST nodes
and provides shell integration to assemble them with NASM.

Supports:
- x86_64 (System V ABI): params in rdi, rsi, rdx, rcx, r8, r9; return in rax
- Labels and jumps
- Data sections (.data, .rodata, .bss)
"""

import os
import re
import platform
import subprocess
from typing import List, Optional, Tuple

import asm_common

PLATFORM = platform.system()
IS_MACOS = PLATFORM == "Darwin"
IS_LINUX = PLATFORM == "Linux"


def generate_nasm_file(
    asm_block, output_path: str, is_arm64: bool = False, format_str: str = "elf64"
):
    """Generate a NASM-compatible .s file from an AsmBlock node.

    Args:
        asm_block: AsmBlock AST node
        output_path: Path to write the .s file
        is_arm64: True for ARM64, False for x86_64 (ignored - NASM is x86 only)
        format_str: Object format ('macho64' or 'elf64')
    """
    is_macos = IS_MACOS and format_str == "macho64"
    symbol_prefix = "_" if is_macos else ""

    with open(output_path, "w") as f:
        f.write("; Generated by Hypotenuse Compiler\n")
        f.write(f"; Target: x86_64 format: {format_str}\n\n")

        _generate_x86_asm(asm_block, f, symbol_prefix, is_macos)


def _generate_x86_asm(asm_block, f, symbol_prefix: str, is_macos: bool = False):
    """Generate x86_64 NASM assembly."""
    directives = []
    instructions = []

    for line in asm_block.lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("syntax"):
            continue
        # Labels end with : and are not directives
        if stripped.endswith(":"):
            instructions.append(stripped)
        elif (
            "section" in stripped
            or stripped.startswith(".")
            or stripped.startswith("global")
        ):
            directives.append(stripped)
        else:
            instructions.append(stripped)

    param_map = asm_common._build_param_map(
        asm_block.params, asm_common.X86_INT_REGS, asm_common.X86_FLOAT_REGS, is_arm64=False
    )

    updated_instructions = asm_common._process_instructions(
        instructions, param_map, is_arm64=False
    )

    data_lines = _build_data_section(asm_block.variables, symbol_prefix, is_arm64=False)
    if data_lines:
        f.write("section .data\n")
        for dl in data_lines:
            f.write(f"{dl}\n")
        f.write("\n")

    has_text_section = any(".text" in d or "section" in d for d in directives)
    if not has_text_section:
        f.write("section .text\n")

    for d in directives:
        if ".data" not in d.lower():
            f.write(f"{d}\n")

    if asm_block.is_function and asm_block.name:
        global_name = f"{symbol_prefix}{asm_block.name}"
        f.write(f"global {global_name}\n")
        f.write(f"{global_name}:\n")

        f.write("    push rbp\n")
        f.write("    mov rbp, rsp\n")

        for param_type, param_name in asm_block.params:
            if param_type in ("float", "double"):
                reg = param_map.get(param_name, "")
                if reg.startswith("xmm"):
                    f.write("    sub rsp, 8\n")
                    f.write(f"    movsd [rsp], {reg}\n")

        for instr in updated_instructions:
            instr_lower = instr.strip().lower()
            if instr_lower == "ret":
                continue
            f.write(f"    {instr}\n")

        asm_common._emit_return_expr(f, asm_block.return_expr, asm_block.ret_type, is_arm64=False)

        f.write("    pop rbp\n")
        f.write("    ret\n")
    else:
        for instr in updated_instructions:
            f.write(f"{instr}\n")
        if asm_block.return_expr is not None:
            asm_common._emit_return_expr(f, asm_block.return_expr, asm_block.ret_type, is_arm64=False)
            f.write("    ret\n")


def _build_data_section(
    variables: List[dict], symbol_prefix: str, is_arm64: bool
) -> List[str]:
    """Build data section lines for variables."""
    lines = []
    if not variables:
        return lines

    for var_info in variables:
        name = var_info["name"]
        var_type = var_info["type"]
        array_size = var_info.get("size")
        initializer = var_info.get("initializer")

        symbol_name = f"{symbol_prefix}{name}"
        lines.append(f"global {symbol_name}")
        lines.append(f"{symbol_name}:")

        if is_arm64:
            if var_type == "string":
                escaped = asm_common._escape_string(initializer or "")
                lines.append(f'    .asciz "{escaped}"')
            elif var_type == "char":
                if array_size:
                    lines.append(f"    .fill {array_size}, 1, {initializer or 0}")
                else:
                    lines.append(f"    .byte {initializer or 0}")
            elif var_type in ("int", "long"):
                lines.append(f"    .long {initializer or 0}")
            elif var_type == "float":
                lines.append(f"    .float {initializer or 0}")
            elif var_type == "double":
                lines.append(f"    .double {initializer or 0}")
        else:
            type_to_nasm = {
                "string": "db",
                "char": "db",
                "short": "dw",
                "int": "dd",
                "long": "dd",
                "float": "dd",
                "double": "dq",
            }
            nasm_directive = type_to_nasm.get(var_type, "dd")
            if array_size:
                lines.append(
                    f"    times {array_size} {nasm_directive} {initializer or 0}"
                )
            else:
                lines.append(f"    {nasm_directive} {initializer or 0}")

        lines.append("")

    return lines[:-1] if lines else lines


def emit_nasm_file(asm_block, output_path: str, syntax: str) -> str:
    """Emit a NASM-compatible .s file from an AsmBlock node.

    Args:
        asm_block: AsmBlock AST node from parser
        output_path: Path to write the .s file
        syntax: Optional syntax override (e.g., "x86_64_elf")

    Returns:
        The output_path that was written to
    """
    is_arm64, format_str = asm_common.get_asm_config(syntax)
    generate_nasm_file(asm_block, output_path, is_arm64, format_str)
    return output_path


def assemble_with_nasm(asm_path: str, obj_path: str, format_str: str) -> str:
    """Assemble a .s file with NASM.

    Args:
        asm_path: Path to the .s file
        obj_path: Optional output path for .o file (defaults to same dir with .o extension)
        format_str: Object format ('macho64' or 'elf64'). Auto-detected if not provided.

    Returns:
        Path to the generated object file

    Raises:
        RuntimeError: If NASM is not found or assembly fails
    """
    import shutil

    if not shutil.which("nasm"):
        raise RuntimeError("nasm not found in PATH. Install NASM: brew install nasm")

    if obj_path is None:
        base, _ = os.path.splitext(asm_path)
        obj_path = base + ".o"

    if format_str is None:
        is_arm64, format_str = asm_common.get_asm_config(None)

    result = subprocess.run(
        ["nasm", "-f", format_str, asm_path, "-o", obj_path],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        raise RuntimeError(f"NASM assembly failed: {result.stderr}")

    return obj_path


def emit_and_assemble(asm_block, output_path: str, syntax: str) -> str:
    """Generate and assemble an asm block in one step.

    Args:
        asm_block: AsmBlock AST node
        output_path: Optional output path (defaults to <name>.o where name is asm func name)
        syntax: Syntax override

    Returns:
        Path to the generated object file
    """
    _, format_str = asm_common.get_asm_config(syntax)

    if output_path is None:
        name = asm_block.name or "asm_block"
        output_path = f"{name}.o"

    asm_path = os.path.splitext(output_path)[0] + ".s"

    emit_nasm_file(asm_block, asm_path, syntax)
    return assemble_with_nasm(asm_path, output_path, format_str)


def print_asm_block(asm_block, is_arm64: bool = False):
    """Print an asm block to stdout in assembly format.

    Args:
        asm_block: AsmBlock AST node
        is_arm64: Ignored - NASM is x86_64 only
    """
    directives = []
    instructions = []

    for line in asm_block.lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("syntax"):
            continue
        # Labels end with : and are not directives
        if stripped.endswith(":"):
            instructions.append(stripped)
        elif (
            stripped.startswith("section ")
            or stripped.startswith("global")
        ):
            directives.append(stripped)
        elif stripped.startswith("."):
            directives.append(stripped)
        else:
            instructions.append(stripped)

    if asm_block.is_function:
        # Asm function
        for directive in directives:
            if "data" in directive.lower() and not directive.startswith("syntax"):
                print(directive)
        if asm_block.data_lines:
            for dl in asm_block.data_lines:
                print(dl)
        for directive in directives:
            if "text" in directive.lower() and not directive.startswith("syntax"):
                print(directive)
            elif not (
                "data" in directive.lower() or "text" in directive.lower()
            ) and not directive.startswith("syntax"):
                print(directive)
        print(f"global {asm_block.name}")
        print(f"{asm_block.name}:")
        for instr in instructions:
            if instr.strip().lower() == "ret":
                continue
            for expanded in asm_common._expand_write_call(instr, is_arm64=False):
                for final_instr in asm_common._expand_len_instruction(expanded, is_arm64=False):
                    print(f"    {final_instr}")
        print("    ret")
    else:
        # Bare asm block
        for directive in directives:
            if "data" in directive.lower() and not directive.startswith("syntax"):
                print(directive)
        if asm_block.data_lines:
            for dl in asm_block.data_lines:
                print(dl)
        for directive in directives:
            if not "data" in directive.lower() and not directive.startswith("syntax"):
                print(directive)
        for line in instructions:
            for expanded in asm_common._expand_write_call(line, is_arm64=False):
                for final_instr in asm_common._expand_len_instruction(expanded, is_arm64=False):
                    print(final_instr)
