name: Makefile CI
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install dependencies
      run: make install

    - name: Lint
      run: make lint

    - name: Build
      run: make build

    - name: test check
      run: make test
